### ISSUE TITLE
Upgraded to Omeka 2.6.1

### ISSUE THREAD

**Issue by jcmundy** [Daniel-KM/Omeka-plugin-OpenLayersZoom#4]
The site is not finding my zoom_tiles or displaying them on the show page.  Do you have any tips on what I might be missing?  The files are in the right location and the div shows up for the class openlayerszoom-images, but it's empty.

**Comment by jcmundy** [comment]
It creates the files if I try to zoom new images, but it doesn't display them either.

**Comment by Daniel-KM** [comment]
There is no particular requirement, the plugin works once installed. The plugin creates tiles in `files/zoom_tiles` manually when the box is checked in the item form, or via the script at the root of the plugin.
The display is automatic when you append the viewer and the js/css inside the config of the plugin, else via the theme.
The file path in the config should be the absolute path to the zoom_tiles directory, for example /var/www/html/Omeka/files/zoom_tiles

**Comment by jcmundy** [comment]
We are using Dreamhost and, while creating the tiles works, it cannot seem to find them no matter how we set up the url in config.

**Comment by jcmundy** [comment]
The viewer does not load no matter if I include the js/css from the header or the plugin config.  I get an empty (though with id) div:
```<div class="openlayerszoom-images"><div id="map-54" class="map"></div>
</div>
```

**Comment by Daniel-KM** [comment]
I find the issue. You use the last version (2.8.2), but this version requires that the scripts to be echoed in the footer, as it is recommended for performance reasons. I just added a new option in config for that (2.8.3), to be published soon.

**Comment by Daniel-KM** [comment]
I find the issue. You use the last version (2.8.2), but this version requires that the scripts to be echoed in the footer, as it is recommended for performance reasons. I just added a new option in config for that (2.8.3).
